services:
  backend:
    container_name: backend
    image: php:8.3.18RC1-fpm-alpine3.21
    working_dir: /backend
    volumes:
      - ./backend:/backend
    entrypoint: >
      sh -c "
        [ -d vendor ] && rm -rf vendor || echo 'backend vendor does not exist';
        apk add --no-cache bash curl git unzip &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer --version &&
        composer install && 
        php -S localhost:1111
      "
    ports:
      - "1111"
  web:
    container_name: web
    image: httpd:alpine3.21
    ports:
      - "${WEB_PORT_DEV}:80"